### ISSUE TITLE
Duplicate __typename in generated query string if included in query used for codegen

### ISSUE THREAD

**Issue by martinohman** [apollostack/apollo-codegen#13]
When I generate Swift-code from a query that include __typename there is duplication in the Query class.

```graphql
query Foo($id: ID!) {
    bar {
        __typename
        ... on bazType {
            ..
        }
    }
}
```

Generate code like:

```swift
public static let operationDefinition =
"query Foo($id: ID!) {" +
"  bar {" +
"    __typename" +
"    __typename" +
"    ... on bazType {" +
"      .." +
"    }" +
"  }" +
"}"

```

While it is easy to avoid including it in the query, it seem reasonable to handle this.

**Comment by martijnwalraven** [comment]
Thanks for the report! This is definitely something we should fix.

**Comment by martijnwalraven** [comment]
For now, I've added a validation rule to prevent this, so we can at least output a useful error message instead of generating invalid code. I've also added a rule to check if `__typename` is used as an alias.

In the future, we may want to not add the field automatically when it is already included, but even then the alias rule should stay in place because we need to be able to rely on `_typename` in the response being what we expect it to be.

Note that `__typename` currently gets special treatment: it only gets added to the query when we cannot statically determine the object type, but it is always available on the model (and will be a constant if querying for it is not needed). This may be trying to be too smart, and there could be edge cases it doesn't take into account, so I'm open to removing this optimization if it turns out to be a problem.
