### ISSUE TITLE
GraphQL custom Scalar types are now all 'String' in Swift

### ISSUE THREAD

**Issue by ephemer** [apollostack/apollo-codegen#3]
We were relying on the GraphQL type names coming in as described in GraphQL, so we could add our own typealiases and conversion code in Swift. For example we had:

```
public extension OurGeneratedQueryType {
    public typealias ID = String
    public typealias ResourceURL = URL
}
```

What's more, we have certain types notated as `Double`s in our Schema, which used to arrive in Swift as `Double`s. Since the change these are all `String`s. Using GraphQL's built-in `Float` type is not a good compromise here, since we want to keep the precision of the `Double` type (from what I've read, Javascript / MongoDB floating point numbers have double precision).

**By changing everything to a `String` at the codegen stage we're losing valuable type information – type information which in my opinion is the whole point of using Apollo-iOS / codegen.**

If the aim of this change was to simplify the developer experience for beginners, maybe it'd be a good compromise to generate a block that the user can then override themselves if needed? Like this:

```
public extension GeneratedQueryType {
    public typealias ID = String
    public typealias CustomScalarType = String
    etc...
}
```

That way users can create their own conversion code for specific Scalars without coupling the conversion code to specific queries.

**Comment by martijnwalraven** [comment]
There wasn't any special handling for custom scalar types in the codegen before, so it generated code that wouldn't compile by default because the type had not been defined. I changed it to `String` to at least make it compile and get reasonable behavior until we could find a more permanent solution.

Glad to hear you found this previous unintentional behavior useful :) I agree we should definitely make custom scalar type mappings work properly, so let's make sure we fix this.

I like your suggestion of generating typealiases by default that can be overridden. I'm not sure we want these typealiases to be per-query however, because custom scalar types are part of the schema and not query specific. But then having them at the top-level may make it impossible to override them. 

Maybe we should namespace them in a struct so you get something like `CustomScalar.ResourceURL`?

**Comment by martijnwalraven** [comment]
Maybe we could also use that struct to allow you to define a custom decoding function, so you can deal with cases where the same basetype needs to be decoded in different ways for different GraphQL scalar types.

**Comment by martijnwalraven** [comment]
Hmmm, on second thought, it seems overriding a typealias isn't possible either at the top-level or at another scope. They both give me an 'Invalid redeclaration' error, which makes sense.

**Comment by ephemer** [comment]
@martijnwalraven it's true, you can't override typealiases or other type definitions in Swift, I used the wrong term of art to describe what I mean. I meant that the user can change the generated code themselves, if codegen makes it obvious enough. I have another idea though:

I recognise that making the beginner experience easy is also an important goal. Maybe we can just have a per-run command line flag that disables the automatic type changes to `String`, and leave it on by default.

**Comment by martijnwalraven** [comment]
Yeah, I really don't want to encourage people changing the generated code, because it is meant to be (potentially) regenerated at every build.

Adding a command line flag to `apollo-codegen` is certainly a good possibility, but I wonder if we can't do better than simply passing through the GraphQL type in the case where we don't map it to `String`.

It may work for simple cases, but I suspect not having any further configuration options quickly breaks down. What about the case where you want to map a custom scalar to a `Date` but rely on a specific date format to do the decoding/encoding for example?

It seems ideally we'd want a solution where:
- Developers don't have to modify the generated code
- The generated code works by default, although with a `String` mapping
- Developers can specify their own mappings for specific custom scalar types
- The types this maps to can be ordinary built-in Swift types (like URL or Date) where appropriate
- Developers can specify their own decoding/encoding behavior for specific scalar types (so not just for the type it is mapped to)

Maybe I'm overthinking this and a simple boolean flag is enough for now, but I'm curious to hear what you think about these points (how important they would be to you for example).

**Comment by martijnwalraven** [comment]
I'm also curious why with the previous codegen behavior you needed to change the generated code at all. Couldn't you have defined `public typealias ResourceURL = URL` at the top level in a separate file?

**Comment by ephemer** [comment]
I think what you outline could be a good next-level solution to this for the longer term. In the meantime a Boolean flag would be a quick solution to allow us and others to use the latest version of codegen today (I've just reverted to the old generated file for now, but presumably this will be impossible in the future).

Re: the typealias, that's exactly what we did (the extension is in another file). But we deliberately extend restricted to within the Query because we create our own structs from the GraphQL results. For a few reasons it's not ideal for us to use the GraphQL models directly right now.

**Comment by martijnwalraven** [comment]
Yes, I agree a boolean flag is probably the best temporary solution for now. I'll try to get it in for the next patch release.

I'd be interested in hearing more about why the generated models are not suitable for you right now however, and why you have to create your own structs. What is keeping you from using or extending the generated structs directly? Is there anything we could do differently in the code generator or runtime support?

**Comment by ephemer** [comment]
Ok great!

Re: the generated structs - the structs we are making are shared between various frameworks, most of which have / should have no knowledge of Apollo. Part of the reason for this is because large parts of the code are shared between iOS and Android (we were the crazy ones who did this: https://medium.com/@ephemer/why-we-put-an-app-in-the-android-play-store-using-swift-96ac87c88dfc#.so5xmh5ke).

In short, we query data in one of our frameworks via Apollo, and the other frameworks use and process the same types. So we convert the queried data into the standard shared type. It's a pretty non-standard use case. But even if that wasn't the case I would find the GraphQL-specific extensions on the type to be somewhat of a hinderance aesthetically (irrelevant entries in the code-completion) and potentially also in terms of performance in critical code paths.

**Comment by martijnwalraven** [comment]
Wow, that is pretty crazy indeed! But it looks like you pulled it off!

It seems yours is a fairly non-standard use case, but it's interesting to keep an eye on this and see if more people feel the same. The way I've been thinking about this is to view the generated query-specific types as similar to a ViewModel, so closely tied to the UI components that access the data. The idea is that you would be editing the GraphQL and UI code side by side, so it doesn't feel like a problem that UI code has some knowledge of GraphQL-specific constructs like fragments.

The next big feature I'm planning on working on is going to be caching, and that will likely mean the structs won't use stored properties but call into a shared (immutable) cache record. So I think we'd like to keep control over how these generated types are constructed. 

If you have any other thoughts or ideas on this, please let me know!

**Comment by ephemer** [comment]
@martijnwalraven yes in terms of ViewModel I guess it also makes sense to have access to e.g. Mutations too from within the View. So I'm a bit torn, it'd be nice to have plain structs constructed by GraphQL (like the ones we are creating now manually), but I can see that there are some advantages to the GraphQL extra for many (most?) users.

Thanks for taking time for this discussion today, much appreciated

**Comment by martijnwalraven** [comment]
Sure, glad to hear someone is already using this, and these discussions are valuable to learn more about people's needs.

**Comment by martijnwalraven** [comment]
I just published version 0.7.2 of `apollo-codegen`, which includes a temporary `passthrough-custom-scalars` option. Hopefully that will solve your problem until we can find a more permanent solution.

**Comment by ephemer** [comment]
@martijnwalraven great stuff and thanks for working on this so quickly! I won't get a chance to test it this weekend but I'm going to close this issue now. I will comment again if something unexpected happens.

**Comment by onizam95** [comment]
@martijnwalraven  can you please guide how to map Apollo.Date to Simple String in Swift because the type Alias is giving the redeclaration error if i use the 
"public typealias Apollo.Date = String"

Please not that i have to use --passThroughCustomScalars so have to parse the GraphQL Date as well now. 
Any help would be appreciated

**Comment by designatednerd** [comment]
@onizam95 I believe the typealias is generated for you if you use `--passthroughCustomScalars` (which it turns out was not so temporary, three years later 😆) - I believe that's why you're getting a redeclaration error. 

If omitting it doesn't work, please open a new issue and I'll try to help out. Thanks!

**Comment by onizam95** [comment]
@designatednerd  i can't omit it :p Gotta convert Long to Int64 and other Data Types.  But yeah i'll open a new issue 

Thanks
